### ISSUE TITLE
Worldcrash when trying to enter Erebus dim

### ISSUE THREAD

**Issue by ZigTheHedge** [joshiejack/Mariculture#318]
Hello!

Here's a part of crashlog with installed Mariculture (1.2.4.2a) and The Erebus (0.2b). I'm not sure how to disallow Mariculture to replace the blocks in "foreign" biomes using configs, so maybe it should be fixed in the code itself.
```java
java.lang.ArrayIndexOutOfBoundsException: 32895
	at net.minecraft.world.biome.BiomeGenBase.func_150560_b(BiomeGenBase.java:390) ~[ahu.class:?]
	at net.minecraft.world.biome.BiomeGenBase.func_150573_a(BiomeGenBase.java:365) ~[ahu.class:?]
	at mariculture.core.handlers.WorldEventHandler.onReplaceBiomeBlocks(WorldEventHandler.java:66) ~[WorldEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_398_WorldEventHandler_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at erebus.world.ChunkProviderErebus.replaceBlocksForBiome(ChunkProviderErebus.java:271) [ChunkProviderErebus.class:?]
	at erebus.world.ChunkProviderErebus.func_73154_d(ChunkProviderErebus.java:147) [ChunkProviderErebus.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at noppes.npcs.PacketHandlerServer.featherPackets(PacketHandlerServer.java:142) [PacketHandlerServer.class:?]
	at noppes.npcs.PacketHandlerServer.onServerPacket(PacketHandlerServer.java:104) [PacketHandlerServer.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_199_PacketHandlerServer_onServerPacket_ServerCustomPacketEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```
Thanks!

**Comment by LiteraryRecluse** [comment]
It seems to be a common problem, I had the same issue with another mod.
https://github.com/joshiejack/Mariculture/issues/308 - This resolved the issue for me.

**Comment by kotoroshinoto** [comment]
I had a problem too
