### ISSUE TITLE
[1.7.10] [Server thread/ERROR] [FML]: A TileEntity type maritech.tile.TileSponge has throw an exception trying to write state.

### ISSUE THREAD

**Issue by MrBloodowrth** [joshiejack/Mariculture#346]
`[15:32:16] [Server thread/ERROR] [FML]: A TileEntity type maritech.tile.TileSponge has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class maritech.tile.TileSponge is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at cofh.api.energy.TileEnergyHandler.func_145841_b(TileEnergyHandler.java:27) ~[TileEnergyHandler.class:?]
	at maritech.tile.TileSponge.func_145841_b(TileSponge.java:104) ~[TileSponge.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
	at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
`

Reproduse: Place <Mariculture:machines_single:4>, try to right click. Causes client crash.

Mariculture-Deluxe-1.7.10-1.2.4.2a
forge-1.7.10-10.13.4.1614-1.7.10-universal

Let me know if any more info is required. Thank you for your time.

**Comment by joshiejack** [comment]
Somehow the registering of my tile entities broke, how I'm not sure, id have to look in to it. However even if i did it would only get fixed in the 1.3.0 dev version.

**Comment by joshiejack** [comment]
What's the mod list

**Comment by MrBloodowrth** [comment]
NotEnoughItems@1.0.5.120,
Thaumcraft@4.2.3.5,
mowziesmobs@1.2.5-undefined,
Waila@1.5.10,
StatusEffectHUD@1.27,
Enchiridion2@2.0.2a,
appliedenergistics2-core@rv2-stable-10,
battlegear2@1.7.10,
BiblioCraft@1.11.4,
OpenModsCore@0.9.1,
betterstorage@0.13.1.127,
ImmersiveEngineering@0.7.6,
wawla@1.3.3,
bspkrsCore@6.16,
mcp@9.05,
animalsPlus@1.2,
MCVanillaTweaks@1.0,
appliedenergistics2@rv2-stable-10,
MutantCreatures@1.4.9,
MobiusCore@1.2.5,
inventorytweaks@1.59-dev-152-cf6e263,
llibrary@0.3.3,
vending@1.2.3,
Mariculture@1.7.10-1.2.4.2a,
BiomesOPlenty@2.1.0,
ExtraUtilities@1.2.12,
Railcraft@9.10.0.0,
OpenBlocks@1.5.1,
EnderStorage@1.4.7.38,
RadixCore@2.1.1,
dungeonpack@1.7.10-1.0,
BiomeTweaker@2.0.182,
eplus@3.0.2-d,
MapWriter@2.1.2,
RTG@0.7.0,
neiintegration@1.1.2,
AWWayofTime@v1.3.3,
Enchiridion@1.3,
FastCraft@1.23,
Forge@10.13.4.1614,
IronChest@6.0.62.742,
Opis@1.2.5,
MariTech@1.0,
thaumicenergistics@1.0.0.5-RV2,
CodeChickenCore@1.0.7.47,
AnimationAPI@1.2.4,
zeldaswordskills@1.7.10-2.4,
XaeroMinimap@1.8.5.2,
MineTweaker3@3.0.10,
modtweaker2@0.9.5,
chocolateQuest@1.0,
FML@7.10.99.99,
TravellersGear@1.16.6,
ThE-core@1.0.0.1,
aquaticabyss@1.1.1,
Baubles@1.0.1.10,
ArmorStatusHUD@1.28,
witchery@0.24.1,
enhancedportals@3.0.12,
OpenMods@0.9.1
